# server config
server:
  port: 9081


# spring config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.49.152:3306/quasar_blog_dev?allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 950714ls


# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: cn.quasar.blog


